// remove all the keys not requried
const stylemap: Record<string, string> = {
    header: null,
    header_1: null,
    header_2: null,
    header_3: null,
    header_4: null,
    header_5: null,
    header_6: null,
    header_icon: null,
    anchor: null,
    button: null,
    bold: null,
    italic: null,
    span: null,
    striked: null,
    paragraph: null,
    code: null,
    preformatted: null,
    blockquote: null,
    horizontal_line: null,
    image: null,
    list: null,
    unorderd_list: null,
    ordered_list: null,
    list_item: null,
    table: null,
    table_head: null,
    table_head_cell: null,
    table_body: null,
    table_row: null,
    table_data: null,
};
